BIN_PATH = 'binary_path'
BIN_NAME = 'binary_name'
CONVERT_CHARS = 'convert_chars'
RESULTS_DIR = 'results_dir'
TIMEOUT = 'timeout'
STATS = 'stats'
IGNORE = 'ignore'

TIME_SPENT = 'time_spent'
F_CALLED = 'f_called'