BIN_PATH = 'binary_path'
BIN_NAME = 'binary_name'
CONVERT_CHARS = 'convert_chars'
RESULTS_DIR = 'results_dir'
PATHS_DIR	= 'paths_dir'
SAVE_PATHS	= 'save_paths'
TIMEOUT = 'timeout'
STATS = 'stats'
IGNORE = 'ignore'

TIME_SPENT = 'time_spent'
F_CALLED = 'f_called'
F_NAMES = 'f_names'

SYM_VAR = 'symvar'